apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: node-app:1.3
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: node-app-config
        - secretRef:
            name: node-app-secret
        env:
        
